# Ruby linting configuration.
# We only worry about two kinds of issues: 'error' and anything less than that.
# Error is not about severity, but about taste. Simple style choices that
# never have a great excuse to be broken, such as 1.9 JSON-like hash syntax,
# are errors. Choices that tend to have good exceptions in practice, such as
# line length, are warnings.

# If you'd like to make changes, a full list of available issues is at
#   https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
# A list of configurable issues is at:
#   https://github.com/bbatsov/rubocop/blob/master/config/default.yml
#
# If you disable a check, document why.

inherit_gem:
  rubocop-github:
  - config/default.yml # generic Ruby rules and cops

require:
- rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'lib/elastomer/client/rest_api_spec/api_spec_*.rb' # Exclude generated ApiSpec files
