#!/bin/sh
set -ex

cd "$(dirname "$0:a")/.."
if bundle check 1>/dev/null 2>&1; then
    echo "Gem environment up-to-date"
else
    echo "Installing gem dependencies"
    exec bundle install "$@"
    exec bundle binstubs --all
fi
