#!/bin/sh
# Usage: script/cibuild
# CI build script.
# This is tailored for the janky build machines.
set -e

# change into root dir and setup path
cd $(dirname "$0")/..
PATH="$(pwd)/bin:$(pwd)/script:/usr/share/rbenv/shims:$PATH"

# Write commit we're building at
git log -n 1 || true
echo

result=0

export RBENV_VERSION="2.3.3"
if [ -d /usr/share/rbenv/shims ]; then
    export PATH=/usr/share/rbenv/shims:$PATH
fi
ruby -v
rm Gemfile.lock
script/bootstrap
bundle exec rake test || result=$?

if [ $result -ne 0 ]; then
    exit $result
fi

# echo
# echo "Running benchmarks"
# script/benchmark
