#!/bin/sh
# Usage: script/cibuild
# CI build script.
# This is tailored for the janky build machines.
set -e

# change into root dir and setup path
cd $(dirname "$0")/..
PATH="$(pwd)/bin:$(pwd)/script:/usr/share/rbenv/shims:$PATH"

# Write commit we're building at
git log -n 1 || true
echo

# Create a snapshot dir and chown it to the es user
export SNAPSHOT_DIR=/tmp/elastomer-client-snapshot-test
mkdir -p $SNAPSHOT_DIR
chown -R elasticsearch $SNAPSHOT_DIR

result=0

export RBENV_VERSION="$(cat .ruby-version)"
echo "Building under $RBENV_VERSION"
script/bootstrap
script/test || result=$?

if [ $result -ne 0 ]; then
    exit $result
fi

# echo
# echo "Running benchmarks"
# script/benchmark
