#!/bin/sh
# Usage: script/cibuild
# CI build script.
# This is tailored for the janky build machines.
set -e

# change into root dir and setup path
cd $(dirname "$0")/..
PATH="$(pwd)/bin:$(pwd)/script:/usr/share/rbenv/shims:$PATH"

# Write commit we're building at
git log -n 1 || true
echo

result=0

echo "Building under 1.8.7"
script/bootstrap
script/testsuite || result=$?
echo

echo "Building under 1.9.3"
export RBENV_VERSION="${1:-1.9.3-p194}"
script/bootstrap
script/testsuite || result=$?

if [ $result -ne 0 ]; then
    exit $result
fi

echo
echo "Running benchmarks"
script/benchmark
