#!/bin/bash
#
# This script will poll the Elasticsearch health endpoint until the cluster
# reaches a yellow state which is good enough for testing. This script will poll
# for up to 30 seconds waiting for Elasticsearch to start. It will give up at
# that time and return a non-zero exit code.

es_port=${ES_PORT:-9200}
count=0

until $(curl -s "localhost:${es_port}/_cluster/health?wait_for_status=yellow&timeout=30s" > /dev/null 2>&1); do
  sleep 0.50
  count=$(($count+1))
  if [ "$count" -gt 60 ]; then
    exit 1
  fi
done
