#!/bin/sh
set -e
cd "$(dirname "$0")/.."

# run entire rspec suite
ruby --version 1>&2
exec ruby -I. -rubygems \
    -r "$(pwd)/spec/spec_helper" \
    -e "ARGV.each { |f| require(f) }" \
    -- $(find spec -name '*_spec.rb')
