# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::MiniTest; end
module ActiveSupport::Notifications; end
module ActiveSupport::Notifications::Event; end
module Gem::Ext::BuildError; end
